apiVersion: 1

# see http://docs.grafana.org/administration/provisioning/
# see http://docs.grafana.org/features/datasources/prometheus/#configure-the-datasource-with-provisioning
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  editable: true
