global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:
- job_name: test-app
  metrics_path: /metrics
  static_configs:
    - targets:
      - 192.168.0.1:8080

- job_name: pushgateway
  honor_labels: true
  static_configs:
    - targets:
      - pushgateway:9091
