global:
  scrape_interval:     5s
  evaluation_interval: 30s

scrape_configs:
- job_name: example-app
  metrics_path: /metrics
  static_configs:
    - targets:
      - host.docker.internal:8080

- job_name: pushgateway
  honor_labels: true
  static_configs:
    - targets:
      - pushgateway:9091
